"""add inquiry_type to contact_message

Revision ID: 3ba7941b51f7
Revises: 603f384949e1
Create Date: 2026-06-11 12:34:47.444673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba7941b51f7'
down_revision = '603f384949e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inquiry_type', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.drop_column('inquiry_type')

    # ### end Alembic commands ###
